"""Build REPORT.md (spec Phase 9) from the analysis tables, never from typed numbers.

* Every section is assembled from the tables and summaries the analyses wrote.
* Every result carries its number of events; regression results are labelled
  "robust" (survives FDR with at least `ROBUST_MIN_EVENTS` events) or
  "suggestive" (everything else).
* A synthetic run writes its report under data/synthetic_run/ with a banner,
  and never touches reports/REPORT.md or the README.
"""

from __future__ import annotations

import datetime as dt
import re
from pathlib import Path

import polars as pl

from printtime.config import Settings
from printtime.panel.store import git_commit

ROBUST_MIN_EVENTS = 15
README_START = "<!-- results:start -->"
README_END = "<!-- results:end -->"


def is_synthetic(cfg: Settings) -> bool:
    return (cfg.paths.calendar / "synthetic_scenarios.parquet").exists()


def _section(path: Path, title: str) -> str:
    if not path.exists():
        return f"## {title}\n\n_Not run yet._\n"
    body = path.read_text().strip()
    body = re.sub(r"^# .*\n?", "", body)  # drop the file's own title
    return f"## {title}\n\n{body}\n"


def _fig(cfg: Settings, name: str, report_dir: Path) -> str:
    p = cfg.paths.figures / name
    if not p.exists():
        return ""
    rel = p.relative_to(report_dir) if p.is_relative_to(report_dir) else p
    return f"![{name}]({rel.as_posix()})\n"


def regression_robustness(cfg: Settings) -> str:
    p = cfg.paths.tables / "reaction_regressions.parquet"
    if not p.exists():
        return ""
    t = pl.read_parquet(p).filter((pl.col("unit") == "ret_ticks") & ~pl.col("mechanical"))
    robust = t.filter(pl.col("survives_fdr") & (pl.col("n_events") >= ROBUST_MIN_EVENTS))
    lines = [
        f"Of {t.height} reaction-function tests, {robust.height} are **robust** (survive the FDR correction "
        f"with at least {ROBUST_MIN_EVENTS} events); the rest are **suggestive** at best.",
        "",
        "| event | instrument | horizon | beta (ticks per 1 SD) | 95% bootstrap | R2 | events | q (BH) | label |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    show = t.filter(pl.col("horizon_s").is_in([1, 60, 1800])).sort(
        ["event_type", "instrument", "horizon_s"]
    )
    for r in show.iter_rows(named=True):
        label = (
            "robust" if r["survives_fdr"] and r["n_events"] >= ROBUST_MIN_EVENTS else "suggestive"
        )
        lines.append(
            f"| {r['event_type']} | {r['instrument']} | {r['horizon_s']} s | {r['beta']:+.2f} | "
            f"[{r['boot_lo']:+.2f}, {r['boot_hi']:+.2f}] | {r['r2']:.2f} | {r['n_events']} | "
            f"{r['q_bh']:.3f} | {label} |"
        )
    return "\n".join(lines) + "\n"


def validation_note(cfg: Settings) -> str:
    p = cfg.paths.tables / "event_validation.csv"
    if not p.exists():
        return ""
    v = pl.read_csv(p)
    bad = v.filter(~pl.col("confirmed"))
    note = f"{v.height - bad.height} of {v.height} releases show a clear volatility spike at the scheduled time."
    if bad.height:
        note += (
            " Not confirmed (checked by hand before use): "
            + ", ".join(bad["event_id"].to_list())
            + "."
        )
    return note


def build_report(cfg: Settings) -> Path:
    synthetic = is_synthetic(cfg)
    out = cfg.paths.reports / "REPORT.md"
    report_dir = out.parent
    banner = (
        "> **SYNTHETIC: NOT RESULTS.** This report was built from the synthetic event generator to check "
        "that the pipeline works end to end. The numbers describe the generator's settings, not markets.\n"
        if synthetic
        else "> Every number below comes from code that ran on CME data in this repository (see the run manifests "
        "next to each table). Consensus figures were compiled by hand and cross-checked against ALFRED.\n"
    )
    text = f"""# Print Time: liquidity and price reaction around U.S. macro releases

_Generated by `printtime report` on {dt.date.today().isoformat()} (git {git_commit()[:10]})._

{banner}
## Questions

1. **Liquidity:** how does the order book change before, at and after CPI, payrolls and FOMC releases, and how long does it take to recover?
2. **Price reaction:** how much does each market move per unit of surprise, which moves first, and does the first move last?
3. **Practice:** when is it safe to trade again, what does execution cost meanwhile, and does trading the surprise pay after costs?

## Data and method

Instruments: {", ".join(cfg.instruments)} (CME Globex, front contract by volume). Sample {cfg.sample.start} to {cfg.sample.end}. Every liquidity result is compared with control days at the same clock time. Event-time panels sample the book at or before each grid point (100 ms and 1 s grids). Intervals are bootstrap intervals that resample whole events. Regressions use HC3 errors with Benjamini-Hochberg false discovery rate control. The strategy is strictly chronological. Details: `docs/explainers/`.

{validation_note(cfg)}

{_section(cfg.paths.tables / "liquidity_summary.md", "1. Liquidity around the release")}
{_fig(cfg, "liquidity_depth_cpi_release.png", report_dir)}
{_fig(cfg, "liquidity_depth_nfp_release.png", report_dir)}
{_fig(cfg, "liquidity_depth_fomc_statement.png", report_dir)}

{_section(cfg.paths.tables / "reaction_summary.md", "2. Who moves first")}
{_fig(cfg, "first_movers.png", report_dir)}

## 3. How much per unit of surprise

{regression_robustness(cfg)}
{_section(cfg.paths.tables / "regression_summary.md", "Regression summary")}
{_fig(cfg, "reaction_heatmap_cpi.png", report_dir)}
{_fig(cfg, "reaction_heatmap_nfp.png", report_dir)}
{_fig(cfg, "reaction_heatmap_fomc.png", report_dir)}

{_section(cfg.paths.tables / "execution_summary.md", "4. What execution costs, and when it is safe again")}
{_fig(cfg, "execution_cpi_release.png", report_dir)}

{_section(cfg.paths.tables / "strategy_summary.md", "5. Does trading the surprise pay?")}
{_fig(cfg, "strategy_pnl.png", report_dir)}

## Where the results are weak

* **Small samples:** about 24 CPI, 24 payrolls and 16 FOMC events. Results with fewer than {ROBUST_MIN_EVENTS} events, or that do not survive the FDR correction, are labelled suggestive.
* **Consensus data** were compiled by hand from news reports; only the actual figures are cross-checked against ALFRED.
* **FOMC surprises** are market-implied from ZT over a 30-minute window and are noisy; ZT's own FOMC regression is mechanical and excluded.
* **Yield conversions** for Treasury futures use rough durations and are approximate.
* **Cross-venue timing:** CBOT, CME, COMEX and NYMEX run separate matching engines; millisecond leads across venues mix real lead-lag with clock differences.
* **No real fills:** execution costs walk the displayed book; hidden liquidity, queue position and market impact on other participants are ignored. Fees are an assumption (${cfg.analysis.execution.fee_per_contract_side_usd:.2f} per contract per side).

## Future work

SR3 (SOFR futures) for a cleaner Kuttner-style FOMC surprise; Tier 2 releases (PPI, retail sales, claims); MBO data for queue position in the execution study; a live Databento feed through the same replay interface.
"""
    text = re.sub(r"\n{3,}", "\n\n", text)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    return out


def update_readme(cfg: Settings, readme: Path) -> bool:
    """Refresh the README results block. Refuses on synthetic runs."""
    if is_synthetic(cfg) or not readme.exists():
        return False
    heads = []
    for name in (
        "liquidity_summary.md",
        "reaction_summary.md",
        "regression_summary.md",
        "execution_summary.md",
        "strategy_summary.md",
    ):
        p = cfg.paths.tables / name
        if p.exists():
            heads += [
                ln for ln in p.read_text().splitlines() if ln.startswith("- ") and "ZN" in ln
            ][:1]
    block = "\n".join(
        [
            README_START,
            "",
            "## Headline results",
            "",
            *heads,
            "",
            "![Depth around CPI](reports/figures/liquidity_depth_cpi_release.png)",
            "![Reaction heatmap](reports/figures/reaction_heatmap_cpi.png)",
            "",
            "Full write-up: [reports/REPORT.md](reports/REPORT.md).",
            "",
            README_END,
        ]
    )
    text = readme.read_text()
    if README_START in text:
        text = re.sub(
            re.escape(README_START) + r".*?" + re.escape(README_END),
            lambda _: block,
            text,
            flags=re.S,
        )
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    readme.write_text(text)
    return True
